sudo: required
services:
- docker
language: go
go:
- 1.9.x
script:
- go build
- docker build -t hacklanta/gifbot .
deploy:
  provider: script
  script: bash docker-push.sh
  on:
    branch: master
env:
  global:
    - secure: rVSOKUpcjtK6Tr4MgkGo3JUijkcoN/6GHZ8AGqD7TWJRDvrHWlybbon1jyMFGniHLSDtQPlK8jAd2L2aqZlJV7ETdCO2ZwuEOg0tmtcBOZRXZNPYnrFx89ppl2TDcKoQZIT91ZNZ2UQQCEouWHS4vgSRLQ/ygRtXXVcqa7GQTqMuqTSJvcn23AbRQ6SMH+ugWjfvGxsbPaD19eQI/BfhQBH9i5eP/5UeRiHp33ptMlQL1yZa2Gy2kPEdejSUcDojqUVW3GqscPvIrvK6CdLRO1/22yrHvyM2MnlJ5t8VWReknyChyEKBonpT2gxZkHPGLvmlUO2JP9pteZ27ZGHf30FPcqwJJpm7i8EkfeeAnOg1J4ceuKJ382A3q9juhplXqgrRyFnkk829sGIUfpIU8KoPtvenCGXMCQpx+4LhkTXKAJZdDERdy5Jhld6/wgD4i+P1XyeU1w4z9bYtcKOBkWd6kCzr96F09pPSwiXvZRGjXYRoaBfKztccekluTStZ71UJcRisBrrJx/xIJ/rJaFt44ayA2Y3hiTvmncNbd/vJ+/jzCZXIDgshwjrGGTuwD+1FCkMEnxr/zaZJGD+Ra3cPEof5MK0tyrzj4oXOOM4f4XbPcGB5ygVAoBey01AbdUIKTmgqFflA8+lMXACU+YJQkXsXvmaKaIjc2Zzx0M0=
    - secure: TRqv3gPg4b0FlPub4lvB5z5mSYsdFS6Opajg9Ih0Tx5oZ4YTNMmjZV0kCHjKgC3b953OJbo+migTcmPCF5OYZI+MLRKFfRlNfk/hIEeBQgobdzjCWvV5GkaTYuNwY0Ozm8ozLBegSwlIfdZ8gSfPM4w9KG0rP0oFI/RiuVfKVlp8oPYNFgAch9qptMNiXOSaA+Ljke57d6NLSJD18QFtS04B9D0zCU0AmxwpaQLiw3pU92LEI+Pny1RF7HsVMOPNAA7rvIieSUpKLQuJWfQvl0XDIdgQEk8M9oCroGIlVceUD0kmqk8uzsHdVfpOPRquhCpgPpHf1DvjhyMvuzm2F1VRCaduar2b7I+6sTviwYfOT8cQhTnDuQ4HccsWdK5vmyQPofuKVpJ03c1myHiuBpVa5zjh5OsBDxTY9Tk1L7Pz86rG9auGfiPcYyx0rh16H7AOlw3aqZbzG2PMJzZ6W/9t7J6GM9Yilj38Rbv+ged60DRA7bc6ards0oYxIEcLZqVsxj3BSUEZ2GkGHGH/TUPSMvxEwk4fyoOaJUzD1no+YVKVnC9vPR2dPLI4SnZIeVcwp9CRYQz1AEbA1DedPsTV4WL4UI2nL/b5X9YM/Bj0cPE8qc8qp9krw1kHl4QNvnRJZmbjdajwcqvU+mkN+cgqtN2tK4QsH2XYnAcDiS0=
