sudo: required
services:
- docker
language: go
go:
- 1.9.x
script:
- go build
- docker build -t hacklanta/gifbot .
deploy:
  provider: script
  script: bash docker-push.sh
  on:
    branch: master
env:
  DOCKER_PASSWORD:
    secure: qI2GQdypaRZBvExai6HPzlu7wKC55bR0VgxhL0SoBSsi2qan8D5t/eyBsmzzAmfuGUtXAofPrNXdPr4BQJR2ZRnIS5jcmR9PCeiewzYitmusGt+B9x6ma8qLyfbPYia20zv0mVhqGUJlTbr55HXUI4oTFTqYE6HLKVJSqiXE36NmSu7/Vs4ej7BvFazyw/IcgqhdpfshmeqcxshbjvHK29j2itn3tzFbs+lt08jOfyt4mCcGSm3t56648PG9w+/1VNRzpenbiqlsr7aW2otR4Y/7bH4qhGYPdZ0x9xD1dZDmZPFyxB7JKBnGo140FAQ9kaNGLzsmSI3xNm/IM5O2mwbZORXqXkuY3UaMM7anqTQa2fctaVXyYiFVVNIkDpAQN8NaNks18Qa5MijTax4QyrMY7Oj6jOZ/yz3mIwFAw1jC1VAHzDH/EE6keeER2zP2BJV+Qo07L7U4a3vbmpl7ADCF7vlbwkawPXiT9EcJ5ACdr2HWHkHu9hdepsBIuXYN8fsBsWW0zN0xf//1ALlGtSbfFMNg1N4xSqXomYmDw9KQUn8kAvt3L0s6cNPGS9ftOfKSJV6q8/d4N4j3tReKQn9rmpsuzrTSMT+wADSIIsOYlqjKTSJJqdFJt7AHbFONG2W0EbE/0mxD389VkXsC6s/Cc6xHSOqqb9OZ0bXzIqk=
  DOCKER_USERNAME:
    secure: DuOQMuGBJUcIiq64aUO0+WYpQ7SQgloPWOHzeu0dYVeLAV74vAQYxsRVNbcC6jz7tt8eZi1ML4scjpGnFdrF1CLO+HGG0Gj/5/V+xv/ywQxm8Jd8fRqMJrdPwRbR23WpafuY5uVoZkrDL1QsCtzs3CG7gQI/TG3ys29K6tcHNlfWsAL5nrAV4O5HSpBdIggCBNc5rYfrHYQEa2zgO1tA3gkmvPRuQdSc52Z0vddSHcwirIRW+cezZJA7u+Td4m11fuFoc8D/Deir78S0w1b3+geLIwwEUrE4B1vZM7ndNftfAMNs5tuIekeFojHqRDqHitPnw+CSZTthSMpYRIqREuq+dQS08vs99xWyJFUY3XGA+XHlzRGWOu845E9VrOWCOzCOglwblmSXWZiro22eGjm+atkgQF8LuB/yH+brYkwFUpAZ+iGt4QLX06Ao7RAIpw++bVieAfkwwT66/z77DBIgykJyjFPJOvOBkB8BvYRoTraqmF3ilvYMRYyYKYI772jwHbypX4AyIyEbrPnS86d5R2ZxF85g2G5aWqKyUVIV2pbyDEgyfgTRmrUIBdR2EyLiL5e5kQ9kY4UmHx9iAaiVlq2kz2z0hVBKVE46BiaMOvxCLqtKLxbc9cjb2VLiru2TfLwlGMZLfbLsymCOIMk+ocZGYM/gANZ4ydeAVJw=
